# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: DeepArm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - first_joint
    - second_joint
    - third_joint
    - fourth_joint
    - fifth_joint
    - sixth_joint
  sim_control_mode: 1 # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# 关节轨迹控制器
arm_joint_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - first_joint
    - second_joint
    - third_joint
    - fourth_joint
    - fifth_joint
    - sixth_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    first_joint: { trajectory: 0.1, goal: 0.1 }
    second_joint: { trajectory: 0.1, goal: 0.1 }
    third_joint: { trajectory: 0.1, goal: 0.1 }
    fourth_joint: { trajectory: 0.1, goal: 0.1 }
    fifth_joint: { trajectory: 0.1, goal: 0.1 }
    sixth_joint: { trajectory: 0.1, goal: 0.1 }
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10

# MoveIt控制器设置
controller_list:
  - name: arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint
